# Generated by Django 5.2.11 on 2026-06-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                max_length=256, unique=True, verbose_name="Название"
            ),
        ),
    ]
