# Generated by Django 5.2.11 on 2026-06-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_ingredient_name_alter_recipe_cooking_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="short_link",
            field=models.CharField(
                blank=True, max_length=6, unique=True, verbose_name="Короткая ссылка"
            ),
        ),
        migrations.DeleteModel(
            name="RecipeShortLink",
        ),
    ]
