# Generated by Django 5.2.11 on 2026-06-12 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_recipeingredient_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recipefavorites",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"), name="recipes_recipefavorites_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"), name="recipes_shoppingcart_unique"
            ),
        ),
    ]
